- name: Setup
  hosts: all
  tags: setup
  become: true

  roles:
    - { role: geerlingguy.docker, become: true}

  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800
      become: true

    - name: Install docker python lib
      pip:
        name: docker
