---
- name: Setup JupyterHub with Docker
  hosts: servers
  become: true

  tasks:
    - name: Pull the latest JupyterHub Docker image
      docker_image:
        name: quay.io/jupyter/datascience-notebook
        source: pull

    - name: Create directory for Jupyter
      file:
        path: /srv/jupyter/
        state: directory
        owner: "1000"
        group: "1000"
        mode: '0755'

    - name: Create directory for Jupyter work
      file:
        path: /srv/jupyter/work
        state: directory
        owner: "1000"
        group: "1000"
        mode: '0755'

    - name: Run JupyterHub container
      docker_container:
        name: jupyter
        image: quay.io/jupyter/datascience-notebook
        state: started
        restart_policy: always
        ports:
          - "8888:8888"
        volumes:
          - jupyter-work:/home/jovyan/work

    - name: Fetch JupyterHub logs and wait for token
      command: docker logs jupyter
      register: jupyter_logs_output
      until: jupyter_logs_output.stderr | regex_search('token=([a-f0-9]+)', '\\1')
      retries: 10  # Retry 10 times
      delay: 10  # Wait 10 seconds between retries

    - name: Extract the Jupyter token from the logs
      set_fact:
        jupyter_token: "{{ (jupyter_logs_output.stderr | regex_search('token=([a-f0-9]+)', '\\1'))[0] }}"

    - name: Ensure the token was successfully extracted
      fail:
        msg: "Could not extract the Jupyter token."
      when: jupyter_token is not defined

    - name: Fetch the server connection IP address (used for connection)
      set_fact:
        server_ip: "{{ ansible_host }}"

    - name: Display connection URL with token
      debug:
        msg: "You can connect to JupyterHub at http://{{ server_ip }}:8888/lab?token={{ jupyter_token }}"
