- name: Install docker
  hosts: "{{ servers | d([]) }}"
  become: true

  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker
